package com.example.flashpedition.service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.flashpedition.entity.Paket;
import com.example.flashpedition.repository.PaketRepository;

import java.util.List;

@Service
public class PaketService {
    @Autowired
    private PaketRepository paketRepository;
    
    public List<Paket> getAllPaket() {
        return paketRepository.findAll();
    }
    public Paket addPaket(Paket obj){
        if (obj == null) {
            return null; // or throw IllegalArgumentException
        }
        // Id auto-generated by JPA inheritance
        return paketRepository.save(obj);
    }
    public Paket getPaketById(long id){
        return paketRepository.findById(id).orElse(null);
    }
    public Paket updatePaket(long id, Paket obj){
        if (obj == null) {
            return null; // or throw IllegalArgumentException
        }
        Paket existing = paketRepository.findById(id).orElse(null);
        if (existing == null) {
            return null; // or throw NotFound exception
        }
        // Copy Paket-specific fields
        existing.setFragile(obj.getFragile());
        existing.setBerat(obj.getBerat());
        existing.setUkuran(obj.getUkuran());
        existing.setStatus(obj.getStatus());
        // Copy inherited shipment fields
        existing.setResi(obj.getResi());
        existing.setSupplier(obj.getSupplier());
        existing.setPenerimaObj(obj.getPenerimaObj());
        existing.setKurir(obj.getKurir());
        existing.setAlamatAsal(obj.getAlamatAsal());
        existing.setAlamatTujuan(obj.getAlamatTujuan());
        existing.setPembayaranObj(obj.getPembayaranObj());
        return paketRepository.save(existing);
    }
    public void deletePaket(long id){
        paketRepository.deleteById(id);
    }
}