package com.example.flashpedition.service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.flashpedition.entity.Pengiriman;
import com.example.flashpedition.repository.PengirimanRepository;

import java.util.List;

@Service
public class PengirimanService {
    @Autowired
    private PengirimanRepository pengirimanRepository;
    
    public List<Pengiriman> getAllPengiriman() {
        return pengirimanRepository.findAll();
    }
    public Pengiriman addPengiriman(Pengiriman obj){
        if (obj == null) {
            return null; // or throw IllegalArgumentException
        }
        // Id auto-generated by JPA
        return pengirimanRepository.save(obj);
    }
    public Pengiriman getPengirimanById(long id){
        return pengirimanRepository.findById(id).orElse(null);
    }
    public Pengiriman updatePengiriman(long id, Pengiriman obj){
        if (obj == null) {
            return null; // or throw IllegalArgumentException
        }
        Pengiriman existing = pengirimanRepository.findById(id).orElse(null);
        if (existing == null) {
            return null; // or throw an exception
        }
        existing.setResi(obj.getResi());
        existing.setSupplier(obj.getSupplier());
        existing.setPenerimaObj(obj.getPenerimaObj());
        existing.setKurir(obj.getKurir());
        existing.setAlamatAsal(obj.getAlamatAsal());
        existing.setAlamatTujuan(obj.getAlamatTujuan());
        existing.setPembayaranObj(obj.getPembayaranObj());
        return pengirimanRepository.save(existing);
    }
    public void deletePengiriman(long id){
        pengirimanRepository.deleteById(id);
    }
}